version: '3.8'
services:
  mongo:
    image: mongo:focal
    container_name: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    container_name: express
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
  # nest-app:
  #   build: .
  #   volumes:
  #     - ./:/app/
  #   links:
  #     - mongo
  #   ports:
  #     - "3000:3000"
volumes:
  mongodb:
